services:
  - type: web
    name: messmate-backend
    env: docker
    rootDir: backend
    plan: free
    healthCheckPath: /
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true